const actionTypes = {
  FETCH_TASKS: 'FETCH_TASKS',
  FETCH_TASKS_SUCCEEDED: 'FETCH_TASKS_SUCCEED',
  FETCH_TASKS_FAILED: 'FETCH_TASKS_FAILED',
  CHANGE_SORT_TYPE: 'CHANGE_SORT_TYPE',
};

export default actionTypes;
